# Put export COMPOSE_FILE=.devcontainer/docker-compose.yml in .env file in project root
# or in your shell so that you don't have to run docker-compose from this subfolder.
name: masterhotwire
services:
  app:
    user: developer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /app
    environment:
      BRIDGETOWN_ENV: development
      DATABASE_URL: sqlite://db/storage/development.db
      BUNDLE_PATH: vendor/bundle
      PADDLE_TOKEN: "test_bf4cb5669c6c60cc8ccca5e7421"
      PADDLE_PRICE_ID: "pri_01ja5tas8g0pskcekk8y3h81vw"
      BOOK_PDF_PATH: "src/master-hotwire-sample.pdf"
      PORT: 4000
      RODA_SECRET_KEY: e41434b6da34f699a7a795e8bb727c9f036dd39dfaadccced2fb46658ecc76de71ed645aa6d3183d3d599b0a223a0457fb94234b31cecccb9b7171b078e3d18d
    ports:
      - "4000:4000"
