# Put export COMPOSE_FILE=.devcontainer/docker-compose.yml in .env file in project root
# or in your shell so that you don't have to run docker-compose from this subfolder.
name: masterhotwire
services:
  app:
    user: developer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /app
    environment:
      BUNDLE_PATH: vendor/bundle
      PORT: 4000
    ports:
      - "4000:4000"
